Repository AY2425S1-CS2103T-W09-4/tp, pull requests merged in 2024-11, with the labels that each got.

#125 Fix the parseCommand_find in AddressBookParserTest and updated Uml diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/FindCommandPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/FindCommandPredicateTest.java
Labels: priority.Medium, alpha-bug

#141 Add import command branch
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#145 Allow `clean` command to keep the results of the previous find command
  src/main/java/seedu/address/logic/commands/CleanCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Medium, alpha-bug

#143 Update UG and DG for undo command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Task, priority.Medium

#151 Update delete popout
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/deleteConfirmation.png
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Medium

#163 Add introduction to UG
  docs/UserGuide.md
Labels: type.Task

#161 Add "GradYear:" in the UI
  docs/UserGuide.md
  src/main/resources/view/PersonListCard.fxml
Labels: severity.VeryLow

#171 Refactor `clean` implementation
  src/main/java/seedu/address/logic/commands/CleanCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Low

#164 Fix Help alpha bug
  src/main/resources/view/HelpWindow.fxml
Labels: severity.Low, alpha-bug

#166 Add tests for Export
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#175 Fix sequence diagram for undo
  docs/diagrams/UndoSequenceDiagram-Logic.puml
Labels: severity.Low, alpha-bug

#178 Update landing page (docs/index.md)
  docs/UserGuide.md
  docs/index.md
Labels: type.Task

#180 Fix Tag alpha bugs and add tests
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: severity.Low, alpha-bug

#173 Update quick start of UG
  docs/UserGuide.md
  docs/images/TemplateUi.png
Labels: type.Task

#156 Add glossary to UG
  docs/UserGuide.md
Labels: priority.Medium

#199 Email duplication handling for `add` and `edit`
  docs/UserGuide.md
  docs/images/AddCommandExampleUsage.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#165 Add tests for Import Command
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/data/ExportImportTest/invalidFile.csv
  src/test/data/ExportImportTest/validFile.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: priority.High

#198 Update User guide with skeleton of field constraints
  docs/UserGuide.md
Labels: priority.Medium

#182 Alphabug fix delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: alpha-bug

#200 Update version number
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium

#211 Add logging for `clean`
  src/main/java/seedu/address/logic/commands/CleanCommand.java
Labels: priority.Low

#185 Update `add` feature in UG
  docs/UserGuide.md
Labels: type.Task

#215 Change "addressbook.json" to "DorManagerPro.json"
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: severity.Low, alpha-bug

#216 Update UG Name duplication handling and tips and notes and help
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task

#214 Refactor undoable as interface and implement undo for import
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CleanCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/Undoable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#187 Add logging to Export and Import
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: priority.Low

#225 Add Name and Email to field constraints
  docs/UserGuide.md
Labels: priority.Medium

#224 Update import and export features in UG
  docs/UserGuide.md
  docs/images/ExportCommandExampleUsage.png
  docs/images/ExportToFolderExample.png
  docs/images/ImportCommandExampleUsage.png
Labels: priority.Medium

#226 Fix undo sequence diagram
  docs/UserGuide.md
  docs/diagrams/UndoSequenceDiagram-Model.puml
Labels: severity.VeryLow

#221 Clicking on hyperlinks to other sections within the UG works within markdown file but not in the website
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#297 Add field constraints for emergency contact
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium

#300 Add planned enhancements appendix to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#299 Small bug fixes for FAQ hyperlink and json file name and `clean` description
  docs/UserGuide.md
Labels: severity.Low

#304 Miscellaneous improvements to User Guide, such as fixing the `Import` command picture and `Edit` a data file feature
  docs/UserGuide.md
Labels: priority.Medium

#303 Add glossary to User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#301 Add manual testing for clean
  docs/DeveloperGuide.md
  docs/images/CleanManualTestingAfterFindStep1.png
  docs/images/CleanManualTestingAfterFindStep2.png
  docs/images/CleanManualTestingAfterFindStep3.png
  docs/images/CleanManualTestingAfterFindStep4.png
Labels: priority.Medium

#306 Add manual testing for undo in DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#308 Add manual testing for `add`
  docs/DeveloperGuide.md
  docs/images/AddCommandTestSuccessMessage.png
Labels: priority.Medium

#309 Misc changes
  docs/UserGuide.md
Labels: priority.Medium

#210 Fix the user guide format
  docs/UserGuide.md
Labels: priority.Low

#311 Add some extra details about `clean` behavior after a `find` in the UG
  docs/UserGuide.md
Labels: priority.Medium

#310 Fix consistency and formatting in User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FindCommandExampleUsage.png
Labels: priority.Medium

#219 Update DG Use cases
  docs/DeveloperGuide.md
Labels: priority.Low

#316 Change helpMessage.png to fit standardisation
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: priority.Medium

#313 Fix the issue from Pe-dry run
  docs/UserGuide.md
  docs/images/Delete popup.png
  docs/images/deleteConfirmation.png
Labels: priority.Medium

#317 Add manual testing for delete and find
  docs/DeveloperGuide.md
  docs/diagrams/DeletePopupActivityDiagram.puml
Labels: priority.Medium

#323 Add manual testing for edit
  docs/DeveloperGuide.md
Labels: priority.Medium

#319 Update dg manual testing for import, export and saving data
  docs/DeveloperGuide.md
Labels: priority.Medium

#329 Fix html errors
  docs/DeveloperGuide.md
Labels: priority.Medium

#328 Add planned enhancements and challenges
  docs/DeveloperGuide.md
Labels: priority.Medium

#340 Test diagram sizes
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/CleanSequenceDiagram.puml
Labels: priority.Medium

#341 Update model class diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.Medium

#339 Add enhancement
  docs/DeveloperGuide.md
Labels: priority.Medium

#322 Add some implementation details for Import and Export
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/CleanSequenceDiagram.puml
  docs/diagrams/ExportActivityDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
Labels: priority.Medium
